### ISSUE TITLE
how to add image on post 

### ISSUE THREAD

**Issue by shohan4556** [djuelg/Shapez-Theme#13]
please give me an example for adding image on post

**Comment by djuelg** [comment]
Could you explain your problem more precisely?
If you want to add an image to your note or to the details of a todo list item, I'm sorry because this is currently not possible. This feature will be added within the next releases.

**Comment by djuelg** [comment]
A post is written in Markdown, so you can add an image in Markdown style:
```
![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")
```
[Take a look at this cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images)

If you want to have more possibilities to customize the size and position of your image use HTML directly in your Markdown. [Take a look at this tutorial](https://www.w3schools.com/html/html_images.asp)
